version: "3.8"

services:
  db-microservices:
    image: postgres:15
    container_name: postgres_db_microservices
    restart: unless-stopped
    environment:
      POSTGRES_USER: msuser
      POSTGRES_PASSWORD: mspassword
      POSTGRES_DB: microservicesdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata-microservices-last-new:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d

  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"
      - "4222:4222"

  client-gateway:
    build: ./client-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  product-ms:
    depends_on: 
      - db-microservices
    build: ./ms-products
    volumes:
      - ./ms-products/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://msuser:mspassword@db-microservices:5432/microservicesdb

  orders-ms:
    depends_on:
      - db-microservices
    build: ./ms-orders
    volumes:
      - ./ms-orders/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://msuser:mspassword@db-microservices:5432/microservicesdb

  auth-ms:
    depends_on:
      - db-microservices
    build: ./ms-auth
    volumes:
      - ./ms-auth/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3003
      - NATS_SERVERS=nats://nats-server:4222
      - JWT_SECRET=secret
      - DATABASE_URL=postgresql://msuser:mspassword@db-microservices:5432/microservicesdb

  payments-ms:
    depends_on:
      - db-microservices
    build: ./ms-payments
    volumes:
      - ./ms-payments/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3003
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://msuser:mspassword@db-microservices:5432/microservicesdb
    
volumes:
  pgdata-microservices-last-new:
  
